export const QUESTIONS = [
  "What is the best way to make friends at a new job?",
  "How should you handle a grease fire in the kitchen?",
  "What's the most effective way to study for an exam?",
  "How do you properly greet someone in Japan?",
  "What should you do if you get lost in a foreign city?",
  "How do you keep a long-distance relationship strong?",
  "What is the proper way to eat spaghetti?",
  "How should you handle a job interview?",
  "What do you do when your WiFi stops working?",
  "How do you train a dog to sit?",
  "What's the secret to a good night's sleep?",
  "How do you apologize after a big argument?",
  "What's the best way to ask for a raise?",
  "How should you react if you see a bear in the wild?",
  "What's the best method for parallel parking?",
  "How do you cure hiccups?",
  "What should you do on a first date?",
  "How do you deal with a noisy neighbor?",
  "What's the best way to lose weight?",
  "How do you make someone feel better when they're sad?",
  "What's the correct way to shake hands?",
  "How do you start a conversation with a stranger?",
  "What should you pack for a camping trip?",
  "How do you calm down an angry customer?",
  "What's the proper way to tip at a restaurant?",
  "How do you wake up early without feeling tired?",
  "What's the best way to learn a new language?",
  "How should you behave at a fancy dinner party?",
  "What do you do when you forget someone's name mid-conversation?",
  "How do you pick the perfect gift for someone?",
];
