export const QUESTIONS = [
  "What's the worst thing to say on a first date?",
  "How do you become rich overnight?",
  "What's the best way to survive a zombie apocalypse?",
  "How do you impress your crush instantly?",
  "What's the secret to becoming famous?",
  "What should you do if aliens land in your backyard?",
  "How do you win every argument?",
  "What's the best excuse for being late?",
  "How do you become the world's smartest person?",
  "What's the correct way to fight a dragon?",
  "How do you get free pizza for life?",
  "What's the best way to sneak into a movie theater?",
  "How do you become president tomorrow?",
  "What's the best pickup line ever?",
  "How do you train a cat to do your homework?",
  "What's the fastest way to become a superhero?",
  "How do you survive being chased by a goose?",
  "What's the best gift for an alien?",
  "How do you pass an exam without studying?",
  "What's the secret ingredient in grandma's cooking?",
  "How do you stop a volcano from erupting?",
  "What's the best way to escape a haunted house?",
  "How do you become a millionaire with ₹10?",
  "What's the best thing to bring to the moon?",
  "How do you make your teacher give everyone full marks?",
  "What's the worst thing to hear during surgery?",
  "How do you make friends with a tiger?",
  "What's the best use for 1000 rubber ducks?",
  "How do you become invisible?",
  "What's the first thing you'd do if you woke up as a chicken?",
  "How do you defeat a robot army?",
  "What's the best way to spend a billion dollars?",
  "How do you explain the internet to a caveman?",
  "What's the best thing to yell in a library?",
  "How do you become king of the world?",
  "What's the weirdest thing to keep in your pocket?",
  "How do you get out of doing chores forever?",
  "What's the best thing to say after breaking something expensive?",
  "How do you convince people you're a wizard?",
  "What's the ultimate life hack?"
];